routes/backend.php
<?php
Route::middleware(['auth'])->group(function () {
	Route::get('/dashboard', 'BackController@index')->name('be.dashboard');
	Route::middleware(['role:administrador'])->group(function () {
		/*
		|------------------------------------------------------------------------------------------------
		| admin product routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('productos', 'ProductController', ['names' => [
			'index' => 'admin-productos.index',
			'show' => 'admin-productos.show',
			'create' => 'admin-productos.create',
			'store' => 'admin-productos.store',
			'edit' => 'admin-productos.edit',
			'update' => 'admin-productos.update',
			'destroy' => 'admin-productos.destroy',
			'store_image' => 'admin-productos.store_image',
			'destroy_image' => 'admin-productos.destroy_image',
		]]);
		Route::get('datatable/productos', 'ProductController@datatable')->name('superadmin.datatable.products');
		Route::get('estatus/productos/{id}', 'ProductController@status')->name('superadmin.datatable.status.product');

		/*
		|------------------------------------------------------------------------------------------------
		| admin orders routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('pedidos', 'OrderController', ['names' => [
			'index' => 'admin-pedidos.index',
			'show' => 'admin-pedidos.show',
			'create' => 'admin-pedidos.create',
			'store' => 'admin-pedidos.store',
			'edit' => 'admin-pedidos.edit',
			'update' => 'admin-pedidos.update',
			'destroy' => 'admin-pedidos.destroy',
		]]);
		Route::get('datatable/pedidos', 'OrderController@datatable')->name('superadmin.datatable.orders');
		Route::post('estatus/pedidos', 'OrderController@status')->name('superadmin.datatable.status.order');

		/*
		|------------------------------------------------------------------------------------------------
		| admin color routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('colores', 'ColorController', ['names' => [
			'index' => 'admin-colores.index',
			'show' => 'admin-colores.show',
			'create' => 'admin-colores.create',
			'store' => 'admin-colores.store',
			'edit' => 'admin-colores.edit',
			'update' => 'admin-colores.update',
			'destroy' => 'admin-colores.destroy',
		]]);
		Route::get('datatable/colores', 'ColorController@datatable')->name('superadmin.datatable.colors');
		Route::get('estatus/colores/{id}', 'ColorController@status')->name('superadmin.datatable.status.color');

		/*
		|------------------------------------------------------------------------------------------------
		| admin size routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('medidas', 'SizeController', ['names' => [
			'index' => 'admin-medidas.index',
			'show' => 'admin-medidas.show',
			'create' => 'admin-medidas.create',
			'store' => 'admin-medidas.store',
			'edit' => 'admin-medidas.edit',
			'update' => 'admin-medidas.update',
			'destroy' => 'admin-medidas.destroy',
		]]);
		Route::get('datatable/medidas', 'SizeController@datatable')->name('superadmin.datatable.sizes');
		Route::get('estatus/medidas/{id}','SizeController@status')->name('superadmin.datatable.status.size');

		/*
		|------------------------------------------------------------------------------------------------
		| admin use routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('usos', 'UseController', ['names' => [
			'index' => 'admin-usos.index',
			'show' => 'admin-usos.show',
			'create' => 'admin-usos.create',
			'store' => 'admin-usos.store',
			'edit' => 'admin-usos.edit',
			'update' => 'admin-usos.update',
			'destroy' => 'admin-usos.destroy',
		]]);
		Route::get('datatable/usos', 'UseController@datatable')->name('superadmin.datatable.uses');
		Route::get('estatus/usos/{id}', 'UseController@status')->name('superadmin.datatable.status.use');

		/*
		|------------------------------------------------------------------------------------------------
		| admin space routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('espacios', 'SpaceController', ['names' => [
			'index' => 'admin-espacios.index',
			'show' => 'admin-espacios.show',
			'create' => 'admin-espacios.create',
			'store' => 'admin-espacios.store',
			'edit' => 'admin-espacios.edit',
			'update' => 'admin-espacios.update',
			'destroy' => 'admin-espacios.destroy',
		]]);
		Route::get('datatable/espacios', 'SpaceController@datatable')->name('superadmin.datatable.spaces');
		Route::get('estatus/espacios/{id}', 'SpaceController@status')->name('superadmin.datatable.status.space');

		/*
		|------------------------------------------------------------------------------------------------
		| admin anti-slip routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('anti-resbalantes', 'AntiSlipController', ['names' => [
			'index' => 'admin-anti-resbalantes.index',
			'show' => 'admin-anti-resbalantes.show',
			'create' => 'admin-anti-resbalantes.create',
			'store' => 'admin-anti-resbalantes.store',
			'edit' => 'admin-anti-resbalantes.edit',
			'update' => 'admin-anti-resbalantes.update',
			'destroy' => 'admin-anti-resbalantes.destroy',
		]]);
		Route::get('datatable/anti-resbalantes', 'AntiSlipController@datatable')->name('superadmin.datatable.anti-slips');
		Route::get('estatus/anti-resbalantes/{id}', 'AntiSlipController@status')->name('superadmin.datatable.status.anti-slip');

		/*
		|------------------------------------------------------------------------------------------------
		| admin brand routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('marcas', 'BrandController', ['names' => [
			'index' => 'admin-marcas.index',
			'show' => 'admin-marcas.show',
			'create' => 'admin-marcas.create',
			'store' => 'admin-marcas.store',
			'edit' => 'admin-marcas.edit',
			'update' => 'admin-marcas.update',
			'destroy' => 'admin-marcas.destroy',
		]]);
		Route::get('datatable/marcas', 'BrandController@datatable')->name('superadmin.datatable.brands');
		Route::get('estatus/marcas/{id}', 'BrandController@status')->name('superadmin.datatable.status.brand');


		/*
		|------------------------------------------------------------------------------------------------
		| admin pasta routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('pastas', 'PastaController', ['names' => [
			'index' => 'admin-pastas.index',
			'show' => 'admin-pastas.show',
			'create' => 'admin-pastas.create',
			'store' => 'admin-pastas.store',
			'edit' => 'admin-pastas.edit',
			'update' => 'admin-pastas.update',
			'destroy' => 'admin-pastas.destroy',
		]]);
		Route::get('datatable/pastas', 'PastaController@datatable')->name('superadmin.datatable.pastas');
		Route::get('estatus/pastas/{id}', 'PastaController@status')->name('superadmin.datatable.status.pasta');

		/*
		|------------------------------------------------------------------------------------------------
		| admin pasta routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('texturas', 'TextureController', ['names' => [
			'index' => 'admin-texturas.index',
			'show' => 'admin-texturas.show',
			'create' => 'admin-texturas.create',
			'store' => 'admin-texturas.store',
			'edit' => 'admin-texturas.edit',
			'update' => 'admin-texturas.update',
			'destroy' => 'admin-texturas.destroy',
		]]);
		Route::get('datatable/texturas', 'TextureController@datatable')->name('superadmin.datatable.textures');
		Route::get('estatus/texturas/{id}', 'TextureController@status')->name('superadmin.datatable.status.texture');

		/*
		|------------------------------------------------------------------------------------------------
		| admin tiendas routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('tiendas', 'StoreController', ['names' => [
			'index' => 'admin-tiendas.index',
			'show' => 'admin-tiendas.show',
			'create' => 'admin-tiendas.create',
			'store' => 'admin-tiendas.store',
			'edit' => 'admin-tiendas.edit',
			'update' => 'admin-tiendas.update',
			'destroy' => 'admin-tiendas.destroy',
		]]);
		Route::get('datatable/tiendas', 'StoreController@datatable')->name('superadmin.datatable.stores');
		Route::get('estatus/tiendas/{id}', 'StoreController@status')->name('superadmin.datatable.status.store');

		/*
		|------------------------------------------------------------------------------------------------
		| admin galery routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('galeria', 'GaleryController', ['names' => [
			'index' => 'admin-galeria.index',
			'show' => 'admin-galeria.show',
			'create' => 'admin-galeria.create',
			'store' => 'admin-galeria.store',
			'edit' => 'admin-galeria.edit',
			'update' => 'admin-galeria.update',
			'destroy' => 'admin-galeria.destroy',
		]]);
		Route::get('datatable/espacios/{id}', 'GaleryController@datatable')->name('superadmin.datatable.galery.product');

		/*
		|------------------------------------------------------------------------------------------------
		| admin pasta routes
		|------------------------------------------------------------------------------------------------
		|
		*/
		Route::resource('vitrinas', 'ShowCaseController', ['names' => [
			'index' => 'admin-vitrinas.index',

routes/frontend.php
<?php
// Auth::routes();

Route::get('/', 'FrontController@index')->name('fe.home');

Route::get('Autocomplete', 'FrontController@autocomplete');

Route::get('Autocomplete2', 'FrontController@autocomplete_products_page');

Route::get('productos', 'FrontController@products')->name('fe.products');

Route::get('productos/{filter}', 'FrontController@filter')->name('fe.products.filter');

// Route::get('productos/{uses}', 'FrontController@uses_filter')->name('fe.products.uses_filter');

// Route::get('productos/{colors}', 'FrontController@colors_filter')->name('fe.products.colors_filter');

// Route::get('productos/{sizes}', 'FrontController@sizes_filter')->name('fe.products.sizes_filter');

Route::get('producto/{product}', 'FrontController@show_product')->name('fe.show.products');

Route::get('directorio', 'FrontController@directory')->name('fe.directory');

Route::get('directorio/{state}', 'FrontController@show_directory')->name('fe.show.directory');

Route::get('ingresar', 'ClientLogin@showLoginForm')->name('fe.showLoginForm');

Route::post('sigup', 'ClientRegister@register')->name('fe.register');

Route::post('signin', 'ClientLogin@login')->name('fe.login');

Route::post('cerrar-sesion', 'ClientLogin@logout')->name('fe.logout');

Route::middleware(['role:cliente'])->group(function () {

	Route::resource('carrito','CartController');

	Route::post('carrito/solicitud-pedido', 'CartController@storeOrder')->name('storeOrder');

	Route::get('cart/datatable', 'CartController@datatable')->name('datatable.carrito');

	Route::resource('mis-pedidos','MyOrdersController');

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

app/Http/Controllers/FrontEnd/CartController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Gloudemans\Shoppingcart\Facades\Cart;
use App\User;
use App\Product;
use App\Order;
use Session;
use Yajra\Datatables\Datatables;
use DB;
use Carbon\Carbon;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cartItems = Cart::instance('tuceramica')->content();

        // if(auth()->user()->roles[0]->id == 2):

        //     $user = User::find(auth()->user()->id);
            
        //     $asociados = $user->vendedores;

        // endif;

        return view('frontend.carrito', compact('cartItems'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = Product::findOrFail($request->id);

        Cart::instance('tuceramica')->add($product->code, $product->name, $request->qty, $product->price->price, ['coin' => $product->price->coin, 'image' => $product->image[0]->name, 'product_id' => $product->id]);

        return 'Producto enviado al carrito de compras!';
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cart = Cart::instance('tuceramica')->get($id);

        if($request->up_down == 1)
        {
            $cart->qty++;
        }else{
            $cart->qty--;            
        }

        return Cart::instance('tuceramica')->content();
        // return 'Cantidad actualizada!';
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cart  $cart
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Cart::instance('tuceramica')->remove($id);

        return 'Producto eliminado del carrito!';
    }

    public function datatable(Datatables $datatables)
    {

        $cartItems = Cart::instance('tuceramica')->content();

        return $datatables->of($cartItems)
            ->addColumn('code', function($cartItem){
               return $cartItem->id;
            })
            ->addColumn('image', function($cartItem){
               return '<img class="shopping-product" src="'.asset('storage/images/products/'.$cartItem->options->product_id.'/'.$cartItem->options->image).'" style="max-width: 100px;" alt="'.$cartItem->options->image.'">';
            })
            ->addColumn('name', function($cartItem){
                return $cartItem->name;
            })
            ->addColumn('price', function($cartItem){
                return $cartItem->price.$cartItem->options->coin;
            })
            ->addColumn('qty', function($cartItem){
                return '<form method="POST" action="'.route("carrito.update", ":CART_ID").'" id="form-update-'.$cartItem->rowId.'">
                            <div class="input-group quantity-number">
                                '.csrf_field().'
                                '.method_field('PATCH').'
                                <input type="text" class="form-control" value="'.$cartItem->qty.'" id="qty" name="qty">
                                <div class="input-group-btn-vertical">
                                    <div class="btn" onclick="updateData(\'' .$cartItem->rowId. '\')"><i class="fa fa-angle-up"></i>
                                    </div>
                                    <div class="btn" onclick="updateData(\'' .$cartItem->rowId. '\')"><i class="fa fa-angle-down"></i>
                                    </div>
                                </div>
                            </div>
                        </form>';
            })
            ->addColumn('total', function($cartItem){
                return $cartItem->price * $cartItem->qty;
            })
            ->addColumn('acciones', function($cartItem){
                $cadena2 = '<a class="btn-close" href="#" onclick="deleteData(\'' .$cartItem->rowId. '\')"><i class="fa fa-close"></i></a>';
                return $cadena2;
            })->rawColumns(['qty', 'actions', 'image'])->make(true);
    }
}

resources/views/frontend/carrito.blade.php
@extends('layouts.front')
@section('title', 'Carrito')
@section('styles')
@endsection
@section('content')

<!-- Header End -->

<!-- Page Header Begins -->

<div id="page-header">
    <div class="header-bg-parallax" style="margin-top: -90px;">
        <div class="overlay">
            <div class="container text-center">
                <div class="header-description">
                    <h1>Carrito de compras</h1>
                    <div class="breadcrumbs">
                        <ul>
                            <li><a href="{{ route('fe.home') }}">Home</a>
                            </li>
                            <li><a href="{{ route('fe.products') }}">Productos</a>
                            </li>
                            <li><a href="{{ route('carrito.index') }}" class="active">Carrito</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /header-small-nav -->
                </div>
                <!-- /header-description -->
            </div>
            <!-- /container -->
        </div>
        <!-- /overlay -->
    </div>
    <!-- /product-filter -->
</div>

<!-- Page Header End -->

<!-- Cart Table Begin -->

<div class="cart-table">
    <div class="container padding-vertical-100">
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table" id="cart-table">
                        <thead>
                            <tr>
                                <th>Foto</th>
                                <th>Titulo del producto</th>
                                <th>Precio</th>
                                <th>Cantidad</th>
                                <th>Precio total</th>
                                <th></th>
                            </tr>
                        </thead>
                        <!-- /thead -->

                        <tbody>
                          @foreach(Cart::instance('tuceramica')->content() as $cartItem)
                            {{-- expr --}}
                            <tr>
                                <td>
                                    <img class="shopping-product" src="storage/images/products/{{$cartItem->options->product_id}}/{{$cartItem->options->image}}" style="max-width: 100px;" alt="">
                                </td>
                                <td class="product-name">
                                    <p>{{$cartItem->name}}</p>
                                </td>
                                <!-- /product-name -->
                                <td class="product-price">
                                    <h5>{{$cartItem->price}} {{$cartItem->options->coin}}</h5>
                                </td>
                                <!-- /product-price -->
                                <td>
                                  <form method="POST" action="{{route('carrito.update', ':CART_ID')}}" id="form-update-{{$cartItem->rowId}}">
                                    {{csrf_field()}}
                                    {{method_field('PATCH')}}
                                    <div class="input-group quantity-number">
                                        <input type="text" name="qty" id="qty" class="form-control" value="{{$cartItem->qty}}">
                                        <input type="hidden" name="id" value="'{{$cartItem->rowId}}'">
                                        <input type="hidden" name="up_down" id="up_down" value="0">
                                        <div class="input-group-btn-vertical">
                                            <div class="btn" onclick="upQty('{{$cartItem->rowId}}')"><i class="fa fa-angle-up"></i>
                                            </div>
                                            <!-- /btn -->
                                            <div class="btn" onclick="downQty('{{$cartItem->rowId}}')"><i class="fa fa-angle-down"></i>
                                            </div>
                                            <!-- /btn -->
                                        </div>
                                        <!-- /input-group-btn-vertical -->
                                    </div>
                                    <!-- /quantity-number -->
                                  </form>
                                </td>
                                <td class="product-price">
                                    <h5 id="product-price">{{$cartItem->price * $cartItem->qty}} {{$cartItem->options->coin}}</h5>
                                </td>
                                <!-- /product-price -->
                                <td class="text-center"><a class="btn-close" href="#" onclick="deleteData('{{$cartItem->rowId}}')"><i class="fa fa-close"></i></a>
                                </td>
                                <!-- /btn-close -->
                            </tr>
                          @endforeach
                        </tbody>
                        <!-- /tbody -->
                    </table>
                    <!-- /table -->
                </div>
                <!-- /table-responsive -->

            </div>
            <!-- /column -->
        </div>
        <!-- /row -->

        <div class="row">
            <div class="col-md-4 pull-right">
                <div class="shop_measures" >
                    <h4>Total</h4>
                    <ul class="cart-total padding-top-50 margin-bottom-80">
                        {{-- <li>Subtotal:<span class="product-price">Bs 640.000</span>
                        </li>
                        <li>IVA:<span class="product-price">Bs 10.000</span>
                        </li>
                        <li>Envio:<span class="product-price">Bs 10.000</span>
                        </li> --}}
                        <li>Total:<span class="product-price total" id="totally">Bs {{Cart::subtotal()}}</span>
                        </li>
                    </ul>
                    <!-- /cart-total -->
                    <a href="javascript:;" class="btn-form pull-right" onclick="addOrder2()">Enviar solicitud de compra</a>
                </div>
                <!-- /shop_measures -->
            </div>
            <!-- /column -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
{!!Form::open(['route'=>[ 'carrito.destroy', ':CART_ID' ],'method'=>'DELETE', 'id' => 'form-delete'])!!}
{!!Form::close()!!}
{!!Form::open(['route'=>[ 'mis-pedidos.store'], 'method'=>'POST', 'id' => 'form-post-carrito'])!!}
{!!Form::close()!!}
@endsection
@section('scripts')
<script>

var addOrder2 = function(form = $('#form-post-carrito')){          

    var url = form.attr('action');

    var data = form.serialize();

    $.post(url, data, function(response){

        $("#count").load(" #count");
        $(".cart-product-list").load(" .cart-product-list");
        $("#total_price").load(" #total_price");
        $("#cart-table").load(" #cart-table");
        $("#totally").load(" #totally");
        swal({
            title: 'Aprobado!',
            text: response,
            type: 'success',
            timer: '2500'
        })

    });

}
  
var upQty = function(id){

  var form = $('#form-update-'+id);
  
  $('#form-update-'+id+' #up_down').val(1)

  var url = form.attr('action').replace(':CART_ID', id);

  var data = form.serialize();

  $.post(url, data, function(response){
    $("#count").load(" #count");
    $(".cart-product-list").load(" .cart-product-list");
    $("#total_price").load(" #total_price");
    $("#cart-table").load(" #cart-table");
    $("#totally").load(" #totally");
    
    // swal({
    //     title: 'Aprobado y enviado!',
    //     text: response,
    //     type: 'success',
    //     timer: '1500'
    // })
  });

}

var downQty = function(id){

  var form = $('#form-update-'+id);
  
  $("#up_down").attr('value', 0);
  
  var url = form.attr('action').replace(':CART_ID', id);

  var data = form.serialize();

  $.post(url, data, function(response){
    $("#count").load(" #count");
    $(".cart-product-list").load(" .cart-product-list");
    $("#total_price").load(" #total_price");
    $("#cart-table").load(" #cart-table");
    $("#totally").load(" #totally");
    // swal({
    //     title: 'Aprobado y enviado!',
    //     text: response,
    //     type: 'success',
    //     timer: '1500'
    // })
  });

}

var deleteData = function(id){

  var form = $('#form-delete');

  var url = form.attr('action').replace(':CART_ID', id);

  var data = form.serialize();

  swal({
    title: 'Estás seguro?',
    text: "No podrás revertir esto!",
    type: 'warning',
    showCancelButton: true,
    cancelButtonColor: '#d33',
    confirmButtonColor: '#3085d6',
    confirmButtonText: 'Si',
    cancelButtonText: 'No',
  }).then(function () {
    $.post(url, data, function(response){
      $("#cart-table").load(" #cart-table");
      $("#count").load(" #count");
      $(".cart-product-list").load(" .cart-product-list");
      $("#total_price").load(" #total_price");
      $("#totally").load(" #totally");
      table.ajax.reload();
      swal({
          title: 'Aprobado!',
          text: response,
          type: 'success',
          timer: '1500'
      })
    });
  });

}
</script>
@endsection

resources/views/frontend/cart.blade.php
<div class="side-cart">
    <div class="close-btn text-center padding-vertical-30">
        <a class="close-cart" href="#">
            Cerrar
        </a>
    </div>
    <!-- /close-btn -->
    <div class="shoping-cart-box">
        <div class="cart-product-list padding-bottom-20">
            @foreach(Cart::instance('tuceramica')->content() as $cartItem)
                <div class="cart-product">
                    <a href="#">
                        <img alt="{{$cartItem->options->image}}" src="../storage/images/products/{{$cartItem->options->product_id}}/{{$cartItem->options->image}}">
                        </img>
                    </a>
                    <div class="cart-product-info">
                        <div class="product-name">
                            <a href="#">
                                {{$cartItem->name}}
                            </a>
                        </div>
                        <!-- /product-name -->
                        <div class="product-atributes padding-vertical-15">
                            <p class="quantity">
                                Cantidad: {{$cartItem->qty}}
                            </p>
                        </div>
                        <!-- /product-atributes -->
                        <div class="product-price">
                            <p>
                                {{$cartItem->price * $cartItem->qty}} {{$cartItem->options->coin}}
                            </p>
                        </div>
                        <!-- /product-price -->
                        <a class="remove-btn" href="#" onclick="deleteData('{{$cartItem->rowId}}')">
                            <i class="fa fa-close">
                            </i>
                        </a>
                    </div>
                    <!-- /cart-product-info -->
                </div>
            @endforeach
            <!-- /cart-product -->
        </div>
        <!-- /cart-product-list -->
        <div class="cart-prices padding-top-30">
            {{-- <div class="shipping">
                <span class="shipping-text">
                    Envio :
                </span>
                <span class="product-price pull-right">
                    50.000.000,00 Bs
                </span>
            </div> --}}
            <!-- /shipping -->
            <div class="total-price padding-top-15" id="total_price">
                <span class="price-text">
                    Total :
                </span>
                <span class="product-price pull-right">
                    {{Cart::subtotal()}}
                </span>
            </div>
            <!-- /total-price -->
        </div>
        <!-- /cart-prices -->
        <div class="cart-buttons margin-top-30">
            <a class="view-cart-btn" href="{{ route('carrito.index') }}">
                Ver carrito
            </a>
            <a class="checkout-btn margin-top-25" href="javascript:;" onclick="addOrder1()">
                Enviar pedido
            </a>
            <a class="checkout-btn margin-top-25" href="{{ route('mis-pedidos.index') }}">
                Mis pedidos
            </a>
        </div>
        <!-- /cart-buttons -->
    </div>
    <!-- /shoping-cart-box -->
</div>
<!-- /side-cart -->
{!!Form::open(['route'=>[ 'carrito.destroy', ':CART_ID' ],'method'=>'DELETE', 'id' => 'form-delete'])!!}
{!!Form::close()!!}
{!!Form::open(['route'=>[ 'mis-pedidos.store'],'method'=>'POST', 'id' => 'form-post'])!!}
{!!Form::close()!!}
<script>
var addOrder1 = function(form = $('#form-post')){          

    var url = form.attr('action');

    var data = form.serialize();

    $.post(url, data, function(response){
        $("#count").load(" #count");
        $(".cart-product-list").load(" .cart-product-list");
        $("#total_price").load(" #total_price");
        $("#cart-table").load(" #cart-table");
        $("#totally").load(" #totally");
        swal({
            title: 'Aprobado!',
            text: response,
            type: 'success',
            timer: '2500'
        })

    });

}

var deleteData = function(id){

    var form = $('#form-delete');

    var url = form.attr('action').replace(':CART_ID', id);

    var data = form.serialize();

    swal({
        title: 'Estás seguro?',
        text: "No podrás revertir esto!",
        type: 'warning',
        showCancelButton: true,
        cancelButtonColor: '#d33',
        confirmButtonColor: '#3085d6',
        confirmButtonText: 'Si',
        cancelButtonText: 'No',
    }).then(function () {
        $.post(url, data, function(response){
          $("#count").load(" #count");
          $(".cart-product-list").load(" .cart-product-list");
          $("#total_price").load(" #total_price");
          swal({
              title: 'Aprobado!',
              text: response,
              type: 'success',
              timer: '1500'
          })
        });
    });

}
</script>